# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-param'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'unicorn'
gem 'dalli'
gem 'mechanize'
gem 'rainbow'

group :development do
  gem 'shotgun'
end
